#!/bin/bash
USERNAME=
THEMENAME=
SERVERNAME=

ERRORSTRING="Error. Please make sure you've indicated correct parameters"
if [ $# -eq 0 ]
    then
        echo $ERRORSTRING;
elif [ $1 == "live" ]
    then
        if [[ -z $2 ]]
            then
                echo "Running dry-run"
                rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./ $USERNAME@$SERVERNAME:/home/$USERNAME/public_html/wp-content/themes/$THEMENAME
        elif [ $2 == "go" ]
            then
                echo "Running actual deploy"
                rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./ $USERNAME@$SERVERNAME:/home/$USERNAME/public_html/wp-content/themes/$THEMENAME
        else
            echo $ERRORSTRING;
        fi
fi